name: AutoIssueSSLCert

on:
#  schedule:
  # Configure appropriate periodic execution times.
#    - cron: "0 2 1 * *"
  watch:
    types: [started]

env:
    ACME: /home/runner/.acme.sh/acme.sh
    DNSAPI: ${{ secrets.DNSAPI }}
    ZIPPWD: ${{ secrets.ZIPPWD }}
    ACMEMAIL: ${{ secrets.ACMEMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install & Configure ACME.SH
      run: |
        wget -O -  https://get.acme.sh | sh -s email="$ACMEMAIL"
        $ACME --upgrade
        echo "$DNSAPI" >> /home/runner/.acme.sh/account.conf
    - name: Issue & Deploy Certificates
      run: |
        mkdir -p ./Certs
        $ACME --register-account -m "$ACMEMAIL" --server zerossl
        $ACME --issue --server zerossl --dns dns_dp -d *.reiyy.com -d reiyy.com
        $ACME --installcert -d *.reiyy.com --key-file ./Certs/*.reiyy.com.key --fullchain-file ./Certs/*.reiyy.com.cer
        $ACME --register-account -m "$ACMEMAIL" --server google
        $ACME --issue --server google --dns dns_dp -d *.home.reiyy.com -d home.reiyy.com
        $ACME --installcert -d *.home.reiyy.com --key-file ./Certs/*.home.reiyy.com.key --fullchain-file ./Certs/*.home.reiyy.com.cer
        zip -rP "$ZIPPWD" Certs.zip Certs
    - name: Commit
      run: |
        # Replace 'you@example.com' and 'yourname' with your own email and user name
        git config --global user.email zzh040722@gmail.com
        git config --global user.name Reiyy
        git add ./Certs.zip
        git commit -m "Update Certs" -a
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
