name: AutoIssueSSLCert

on:
  schedule:
    - cron: "33 2 1 * *"
  watch:
    types: [started]

env:
    ACME: /home/runner/.acme.sh/acme.sh
    DNSAPI: ${{ secrets.DNSAPI }}
    ZIPPWD: ${{ secrets.ZIPPWD }}
    ACMEMAIL: ${{ secrets.ACMEMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install & Configure ACME.SH
      run: |
        wget -O -  https://get.acme.sh | sh -s email="$ACMEMAIL"
        $ACME --upgrade
        echo "$DNSAPI" >> /home/runner/.acme.sh/account.conf
    - name: Issue & Deploy Certificates
      run: |
        mkdir -p ./Certs
        $ACME --register-account  -m "$ACMEMAIL" --server zerossl
        $ACME --issue --server zerossl --dns dns_dp -d *.yareiy.com -d yareiy.com
        $ACME --installcert -d *.yareiy.com --key-file ./Certs/*.yareiy.com.key --fullchain-file ./Certs/*.yareiy.com.cer
        $ACME --issue --server zerossl --dns dns_cf -d *.yareiy.eu.org -d yareiy.eu.org
        $ACME --installcert -d *.yareiy.eu.org --key-file ./Certs/*.yareiy.eu.org.key --fullchain-file ./Certs/*.yareiy.eu.org.cer
        zip -rP "$ZIPPWD" Certs.zip Certs
    - name: Commit
      run: |
        # Replace 'you@example.com' and 'yourname' with your own email and user name
        git config --global user.email zhzhu722@yareiy.com
        git config --global user.name Reiyy
        git add ./Certs.zip
        git commit -m "Update Certs" -a
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
